CREATE TABLE address (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city VARCHAR(255),
    street VARCHAR(255),
    building VARCHAR(255)
);

CREATE TABLE users (
    id UUID PRIMARY KEY,
    login VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    age INTEGER,
    role VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    address_id INTEGER NOT NULL,
    CONSTRAINT fk_users_address_id FOREIGN KEY (address_id) REFERENCES address(id)
);
